FROM docker.elastic.co/wolfi/jdk:openjdk-25.0.3-r5-dev@sha256:d59ebffca86e0ae84b0aaaec959e81ca02058e89d08cad5be582093c4d1945f2

USER root

WORKDIR /app

COPY . .

ENV GRADLE_OPTS="-Xmx512m -XX:MaxMetaspaceSize=256m"

CMD ["./gradlew", "test", "e2eTest", "--no-daemon", "--info", "--stacktrace"]
