# The new settings format:
# At the top level the label descring the query that will also be used as the
#   file name for its output.
#   Below the query label are the following attributes:
#     * extension - the file extension to be used for output. Optional, defaults to .json.
#     * subdir - some api's are now grouped in a subdirectory of the output directory to lessen clutter. Optional, defaults to root dir.
#     * retry - whether if a query fails it will be retried for the configured number of attempts. Optional, defaults to false.
#     * versions - one or more attributes of the format "version rule: "query string". Each set of version/query key pairs
#       should evaluate to exactly one that is appropriate for the version of the server being queried. Therefor rules should
#       be structured in such a way that only a valid query can be executed against a given version. Required.
#   NPM mode is the only one used: https://github.com/vdurmont/semver4j
#   NPM Versioning rules are documented here: https://github.com/npm/node-semver
#
#   Note to those adding entries: within each group, cat API's, json API's, and commercial, they are in alphabetical order.
#   Please adhere to this convention when submitting pull requests.

## cat API's

cat_aliases:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 0.9.0": "/_cat/aliases?v"

cat_allocation:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 0.9.0": "/_cat/allocation?v"

cat_count:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 0.9.0": "/_cat/count"

cat_fielddata:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 0.9.0": "/_cat/fielddata?v"

cat_health:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 0.9.0": "/_cat/health?v"

cat_indices:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 0.9.0 < 5.1.1": "/_cat/indices?v"
    ">= 5.1.1 < 6.7.0": "/_cat/indices?v&s=index"
    ">= 6.7.0 < 7.7.0": "/_cat/indices?v&s&h=health,status,index,uuid,pri,rep,docs.count,docs.deleted,store.size,pri.store.size,sth"
    ">= 7.7.0": "/_cat/indices?v&s=index&h=health,status,index,uuid,pri,rep,docs.count,docs.deleted,store.size,pri.store.size,sth&expand_wildcards=all"

cat_master:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 0.9.0": "/_cat/master"

cat_nodeattrs:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 2.0.0": "/_cat/nodeattrs?v&h=node,id,pid,host,ip,port,attr,value"

cat_nodes:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 0.9.0": "/_cat/nodes?v&h=n,nodeId,m,i,r,d,hp,rp,cpu,load_1m,load_5m,load_15m,"

cat_pending_tasks:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 0.9.0": "/_cat/pending_tasks?v"

cat_recovery:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 0.9.0 < 7.7.0": "/_cat/recovery?v"
    ">= 7.7.0": "/_cat/recovery?v&expand_wildcards=all"

cat_repositories:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 2.0.0": "/_cat/repositories?v"

cat_segments:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 0.9.0 < 5.1.1": "/_cat/segments?v"
    ">= 5.1.1 < 7.7.0": "/_cat/segments?v&s=index"
    ">= 7.7.0": "/_cat/segments/*,.*?v&s=index"

cat_shards:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 0.9.0 < 5.1.1": "/_cat/shards?v"
    ">= 5.1.1": "/_cat/shards?v&s=index"

#cat_snapshots:
#  extension: ".txt"
#  subdir: "cat"
#  versions:
#    ">= 2.0.0": "/_cat/snapshots"

cat_templates:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 7.8.0": "/_cat/templates?v"

cat_thread_pool:
  extension: ".txt"
  subdir: "cat"
  versions:
    ">= 0.9.0": "/_cat/thread_pool?v"

## Non-cat .txt API
nodes_hot_threads:
  extension: ".txt"
  retry: true
  versions:
    "> 0.9.0": "/_nodes/hot_threads?threads=10000"

## Common JSON API's
alias:
  versions:
    ">= 0.9.0": "/_alias?pretty&human"

allocation:
  versions:
    ">= 0.9.0": "/_cat/allocation?v&format=json"
  showErrors: false

allocation_explain:
  versions:
    ">= 5.0.0": "/_cluster/allocation/explain?pretty"
  showErrors: false

allocation_explain_disk:
  versions:
    ">= 5.0.0": "/_cluster/allocation/explain?include_disk_info=true&pretty"

component_templates:
  retry: true
  versions:
    ">= 7.8.0": "/_component_template"

count:
  versions:
    ">= 2.0.0": "/_count"

cluster_health:
  versions:
    ">= 0.9.0": "/_cluster/health?pretty"

cluster_pending_tasks:
  versions:
    ">= 0.9.0": "/_cluster/pending_tasks?pretty&human"

cluster_settings:
  versions:
    ">= 0.9.0": "/_cluster/settings?pretty&flat_settings"

cluster_settings_defaults:
  versions:
    ">= 6.4.0": "/_cluster/settings?include_defaults&pretty&flat_settings"

cluster_state:
  retry: true
  versions:
    ">= 0.9.0": "/_cluster/state?human"

cluster_stats:
  versions:
    ">= 0.9.0": "/_cluster/stats?pretty&human"

dangling_indices:
  versions:
    ">= 7.9.0": "/_dangling?pretty&human"

fielddata:
  versions:
    ">= 0.9.0": "/_cat/fielddata?format=json&bytes&pretty"

fielddata_stats:
  versions:
    ">= 0.9.0 < 5.0.0": "/_nodes/stats/indices/fielddata?pretty=true&fields=*"
    ">= 5.0.0": "/_nodes/stats/indices/fielddata?level=shards&pretty=true&fields=*"

index_templates:
  retry: true
  versions:
    ">= 7.8.0": "/_index_template"

indices:
  versions:
    ">= 0.9.0 < 5.1.1": "/_cat/indices?format=json&bytes=b&h=index,shard,prirep,state,docs,store,id,node"
    ">= 7.0.0": "/_cat/shards?format=json&bytes=b&s=index&h=index,shard,prirep,state,docs,store,id,node,se,sm,fm,fe,ft,iiti,iito,iitf,idto,idti,ftt,ua,ud,ur"

indices_stats:
  retry: true
  versions:
    ">= 0.9.0 < 7.7.0": "/_stats?level=shards&pretty&human"
    ">= 7.7.0": "/_stats?level=shards&pretty&human&expand_wildcards=all"

licenses:
  versions:
    ">= 1.0.0 < 2.0.0": "/_licenses"
    ">= 2.0.0 < 7.6.0": "/_license?pretty"
    ">= 7.6.0 < 8.0.0": "/_license?pretty&accept_enterprise=true"
    ">= 8.0.0": "/_license?pretty"

mapping:
  versions:
    ">= 0.9.0 < 7.7.0": "/_mapping"
    ">= 7.7.0": "/_mapping?expand_wildcards=all"

master:
  versions:
    ">= 0.9.0": "/_cat/master?format=json"

nodes:
  retry: true
  versions:
    ">= 0.9.0": "/_nodes?pretty&human"

nodes_short:
  versions:
    ">= 0.9.0": "/_cat/nodes?format=json&v&full_id&h=name,id,master,ip,role"

nodes_stats:
  retry: true
  versions:
    ">= 0.9.0": "/_nodes/stats?pretty&human"

nodes_usage:
  versions:
    ">= 6.0.0": "/_nodes/usage?pretty"

pipelines:
  versions:
    ">= 5.0.0": "/_ingest/pipeline/*?pretty&human"

plugins:
  versions:
    ">= 0.9.0": "/_cat/plugins?format=json"

recovery:
  versions:
    ">= 0.9.0": "/_recovery?pretty&human&detailed=true"

remote_cluster_info:
  versions:
    ">= 6.0.0": "/_remote/info"

segments:
  retry: true
  versions:
    ">= 0.9.0": "/_segments?pretty&human"

settings:
  retry: true
  versions:
    ">= 0.9.0 < 7.7.0": "/_settings?pretty&human"
    ">= 7.7.0": "/_settings?pretty&human&expand_wildcards=all"

shard_stores:
  versions:
    ">=2.0.0": "/_shard_stores?pretty"

shards:
  retry: true
  versions:
    ">=0.9.0": "/_cat/shards?format=json&bytes=b&pretty"

snapshot:
  versions:
    ">=7.15.0": "/_snapshot/*/*?verbose=false"

tasks:
  versions:
    ">=2.0.0": "/_tasks?pretty&human&detailed=true"

templates:
  versions:
    ">= 0.9.0": "/_template?pretty"

version:
  retry: true
  versions:
    ">= 0.9.0": "/"

## Commercial Features
autoscaling_capacity:
  subdir: "commercial"
  versions:
    ">= 7.11.0": "/_autoscaling/capacity?pretty"

ccr_autofollow_patterns:
  subdir: "commercial"
  versions:
    ">= 6.5.0": "/_ccr/auto_follow?pretty"

ccr_follower_info:
  subdir: "commercial"
  versions:
    ">= 6.7.0": "/_all/_ccr/info?pretty"

ccr_stats:
  subdir: "commercial"
  versions:
    ">= 6.5.0": "/_ccr/stats?pretty"

enrich_policies:
  subdir: "commercial"
  versions:
    ">= 7.5.0": "/_enrich/policy?pretty"

enrich_stats:
  subdir: "commercial"
  versions:
    ">= 7.5.0": "/_enrich/_stats?pretty"

ilm_explain:
  subdir: "commercial"
  versions:
    ">= 6.6.0": "/*/_ilm/explain?human&pretty"

ilm_policies:
  subdir: "commercial"
  versions:
    ">= 6.6.0": "/_ilm/policy?human&pretty"

ilm_status:
  subdir: "commercial"
  versions:
    ">= 6.6.0": "/_ilm/status?pretty"

logstash_pipeline:
  subdir: "commercial"
  versions:
    ">= 7.12.0": "/_logstash/pipeline"

ml_anomaly_detectors:
  subdir: "commercial"
  versions:
    ">= 5.0.0 < 7.0.0": "/_xpack/ml/anomaly_detectors?pretty"
    ">= 7.0.0": "/_ml/anomaly_detectors?pretty"

ml_datafeeds:
  subdir: "commercial"
  versions:
    ">= 5.0.0 < 7.0.0": "/_xpack/ml/datafeeds?pretty"
    ">= 7.0.0": "/_ml/datafeeds?pretty"

ml_datafeeds_stats:
  subdir: "commercial"
  versions:
    ">= 7.4.0": "/_ml/datafeeds/_stats?pretty"

ml_dataframe:
  subdir: "commercial"
  versions:
    ">= 7.3.0": "/_ml/data_frame/analytics?pretty"

ml_dataframe_stats:
  subdir: "commercial"
  versions:
    ">= 7.3.0": "/_ml/data_frame/analytics/_stats?pretty"

ml_info:
  subdir: "commercial"
  versions:
    ">= 6.3.0 < 7.0.0": "/_xpack/ml/info?pretty"
    ">= 7.0.0": "/_ml/info?pretty"

ml_stats:
  subdir: "commercial"
  versions:
    ">= 5.0.0 < 7.0.0": "/_xpack/ml/anomaly_detectors/_stats?pretty"
    ">= 7.0.0": "/_ml/anomaly_detectors/_stats?pretty"

nodes_shutdown_status:
  subdir: "commercial"
  versions:
    ">= 7.15.0": "/_nodes/shutdown?pretty"

rollup_jobs:
  subdir: "commercial"
  versions:
    ">= 6.3.0 < 7.0.0": "/_xpack/rollup/job/_all"
    ">= 7.0.0": "/_rollup/job/_all"

rollup_caps:
  subdir: "commercial"
  versions:
    ">= 6.3.0 < 7.0.0": "/_xpack/rollup/data/_all"
    ">= 7.0.0": "/_rollup/data/_all"

rollup_index_caps:
  subdir: "commercial"
  versions:
    ">= 6.5.0 < 7.0.0": "/*/_xpack/rollup/data"
    ">= 7.0.0": "/*/_rollup/data"

searchable_snapshots_cache_stats:
  subdir: "commercial"
  versions:
    ">= 7.13.0": "/_searchable_snapshots/cache/stats?pretty&human"

security_priv:
  subdir: "commercial"
  versions:
    ">= 6.5.0 < 7.0.0": "/_xpack/security/privilege?pretty"
    ">= 7.0.0": "/_security/privilege?pretty"

security_roles:
  subdir: "commercial"
  versions:
    ">= 2.0.0 < 5.0.0": "/_shield/role?pretty"
    ">= 5.0.0 < 7.0.0": "/_xpack/security/role?pretty"
    ">= 7.0.0": "/_security/role?pretty"

security_role_mappings:
  subdir: "commercial"
  versions:
    ">= 5.0.0 < 7.0.0": "/_xpack/security/role_mapping?pretty"
    ">= 7.0.0": "/_security/role_mapping?pretty"

security_users:
  subdir: "commercial"
  versions:
    ">= 2.0.0 < 5.0.0": "/_shield/user?pretty"
    ">= 5.0.0 < 7.0.0": "/_xpack/security/user?pretty"
    ">= 7.0.0": "/_security/user?pretty"

slm_policies:
  subdir: "commercial"
  versions:
    ">= 7.4.0": "/_slm/policy?pretty&human"

slm_stats:
  subdir: "commercial"
  versions:
    ">= 7.5.0": "/_slm/stats?pretty"

slm_status:
  subdir: "commercial"
  versions:
    ">= 7.6.0": "/_slm/status"

transform:
  subdir: "commercial"
  versions:
    ">= 7.2.0 < 7.5.0": "_data_frame/transforms?pretty"
    ">= 7.5.0": "_transform?pretty"

transform_stats:
  subdir: "commercial"
  versions:
    ">= 7.2.0 < 7.5.0": "_data_frame/transforms/_stats?pretty"
    ">= 7.5.0": "_transform/_stats?pretty"

watcher_stats:
  subdir: "commercial"
  versions:
    ">= 1.6.0 < 5.0.0": "/_watcher/stats/_all"
    ">= 5.0.0 < 7.0.0": "/_xpack/watcher/stats/_all"
    ">= 7.0.0": "/_watcher/stats/_all"

watcher_stack:
  subdir: "commercial"
  versions:
    ">= 1.6.0 < 5.0.0": "/_watcher/stats?emit_stacktraces=true"
    ">= 5.0.0 < 7.0.0": "/_xpack/watcher/stats?emit_stacktraces=true"
    ">= 7.0.0": "/_watcher/stats?emit_stacktraces=true"

xpack:
  subdir: "commercial"
  versions:
    ">= 5.0.0": "/_xpack/usage?pretty&human"

data_stream:
  subdir: "commercial"
  versions:
    ">= 7.9.0": "/_data_stream?pretty"
