---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: ":gradle: Test"
    key: "gradle-test"
    commands:
      - docker build -f Dockerfile.test -t support-diagnostics-test .
      - docker run --name support-diagnostics-test-run support-diagnostics-test; EXIT_CODE=$$?; docker cp support-diagnostics-test-run:/app/build/reports/tests . || true; docker rm support-diagnostics-test-run; exit $$EXIT_CODE
    artifact_paths:
      - "reports/tests/test/**/*"
    agents:
      provider: "gcp"
      imagePrefix: "core-ubuntu-2204"
      machineType: "n2-standard-2"

  - label: ":docker: Build and Push Docker Image"
    depends_on: "gradle-test"
    if: build.branch == "main"
    plugins:
      - elastic/vault-secrets#v0.1.0:
          path: 'kv/ci-shared/opex/oci-registry-creds-prod'
          field: "username"
          env_var: "DOCKER_REG_USER"
      - elastic/vault-secrets#v0.1.0:
          path: 'kv/ci-shared/opex/oci-registry-creds-prod'
          field: "password"
          env_var: "DOCKER_REG_PASS"
      - elastic/vault-secrets#v0.1.0:
          path: 'kv/ci-shared/opex/oci-registry-creds-prod'
          field: "hostname"
          env_var: "DOCKER_REG_HOSTNAME"
    commands:
      - VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)
      - set +x && echo "$$DOCKER_REG_PASS" | docker login -u "$$DOCKER_REG_USER" --password-stdin "$$DOCKER_REG_HOSTNAME"
      - docker buildx create --use --name multiarch-builder --driver docker-container || docker buildx use multiarch-builder
      - docker buildx build --platform linux/amd64,linux/arm64 --push -t "docker.elastic.co/support/diagnostics:$${VERSION}" .
    agents:
      provider: "gcp"
      imagePrefix: "core-ubuntu-2204"
      machineType: "n2-standard-2"
