---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:

  # if our Renovate configuration is amended, then make sure we have well-formed config
  # for more info, see https://docs.elastic.dev/plat-prod-team/service-catalogue/renovate/testing-renovate-changes
  - label: "Verify Renovate configuration"
    command: "renovate-config-validator"
    agents:
      image: "docker.elastic.co/ci-agent-images/pipelib:0.25.0@sha256:1e7cbd9859c9d4d16471b99c4d734709340d7c584401a62b762ca1592c2e5df0"
    if_changed:
      - "renovate.json"

  # if our catalog-info.yaml is changed, make sure it's well-formed according to our internal standards as well as Backstage's validation
  - label: Validate TokenPolicy RREs
    command: "/agent/check-catalog-info.sh"
    agents:
      image: "docker.elastic.co/ci-agent-images/pipelib:0.25.0@sha256:1e7cbd9859c9d4d16471b99c4d734709340d7c584401a62b762ca1592c2e5df0"
    if_changed:
      - "catalog-info.yaml"

  - label: ":pipeline: Upload default Pipeline"
    command: "buildkite-agent pipeline upload .buildkite/default-pipeline.yml"
    if_changed:
      include:
        - "**/*"
      exclude:
        - "catalog-info.yaml"
        - "renovate.json"
