name: Check NOTICE.txt

on:
  pull_request:

jobs:
  check-notice:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4
        id: changes
        with:
          # If any of these files changed, then we may need to update the NOTICE.txt
          filters: |
            notice:
              - 'build.gradle.kts'
              - 'NOTICE.template'
              - 'NOTICE.txt'
              - 'buildSrc/**'

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        if: steps.changes.outputs.notice == 'true'

      - name: Set up JDK 25
        if: steps.changes.outputs.notice == 'true'
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          cache: gradle
          distribution: zulu
          java-version: '25'

      - name: Generate NOTICE.txt
        if: steps.changes.outputs.notice == 'true'
        run: ./gradlew generateLicenseReport

      - name: Check NOTICE.txt is up to date
        if: steps.changes.outputs.notice == 'true'
        run: |
          if ! git diff --exit-code NOTICE.txt; then
            echo "::error::NOTICE.txt is out of date. Run './gradlew generateLicenseReport' and commit the result."
            exit 1
          fi
